    - name: disable redis
      ansible.builtin.command: dnf module disable redis -y

    - name: enable redis:7
      ansible.builtin.command: dnf module enable redis:7 -y


    - name: install redis
      ansible.builtin.package:
       name: redis
       state: present  

    - name: replace the bind ip
      ansible.builtin.replace:
       path: /etc/redis/redis.conf
       regexp: '127.0.0.1'
       replace: '0.0.0.0'   

    - name: disable protected mode 
      ansible.builtin.lineinfile:
       path: /etc/redis/redis.conf
       regexp: 'protected-mode yes'
       line: 'protected-mode no'   

    - name: start redis service
      ansible.builtin.service:
       name: redis
       state: started
       enabled: true   