- name: configuring mongodb server
  hosts: mongodb
  become: yes
  tasks:
    - name: copy mongodb repo files
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb server
      ansible.builtin.dnf:
       name: mongodb-org
       state: present    

    - name: start mongodb server
      ansible.builtin.service:
       name: mongod
       state: started
       enabled: true  

    - name: replace the bind ip
      ansible.builtin.replace:
       path: /etc/mongod.conf
       regexp: '127.0.0.1'
       replace: '0.0.0.0'

    - name: restart mongodb server
      ansible.builtin.service:
        name: mongod
        state: restarted   