
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y
      

    - name: enabled nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present     

    - name: create user for catalogue
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    -  name: create app directory
       ansible.builtin.file:
        path: /app
        state: directory


    - name: download catalogue code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp

    # - name: current directory
    #   ansible.builtin.command: cd /app    

    - name: unzip the catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue-v3.zip
        dest: /app  
        remote_src: yes    

    - name: install nodejs dependencies
      community.general.npm:
        path: /app

    - name: copying catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service    

    - name: deamon reload service
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: true    


    - name: copy mongodb repo files
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check products loaded or not
      ansible.builtin.command: mongosh --host mongodb.prudhvi.shop --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print catalogue_output
      ansible.builtin.debug:
       msg: "{{ catalogue_output }}"  

    - name: load catalogue schema
      ansible.builtin.shell: mongosh --host mongodb.prudhvi.shop </app/db/master-data.js
      when: catalogue_output.stdout | int < 0 



  