
    - name: app setup tasks
      include_role: 
        name: common
        tasks_from: app-setup

    - name: nodejs tasks
      include_role:
        name: common
        tasks_from: nodejs



 


    - name: copy mongodb repo files
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check products loaded or not
      ansible.builtin.command: mongosh --host mongodb.prudhvi.shop --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print catalogue_output
      ansible.builtin.debug:
       msg: "{{ catalogue_output }}"  

    - name: load catalogue schema
      ansible.builtin.shell: mongosh --host mongodb.prudhvi.shop </app/db/master-data.js
      when: catalogue_output.stdout | int < 0 


    - name: systemd tasks
      include_role:
        name: common
        tasks_from: systemd    


  