    - name: copying {{ component }} service file
      ansible.builtin.template:
        src: "{{ component }}.service.j2"
        dest: /etc/systemd/system/{{ component }}.service    

    - name: deamon reload service
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and enable {{ component }} service
      ansible.builtin.service:
        name: "{{ component }}"
        state: restarted
        enabled: true   