

    - name: deamon reload service
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: true   