- name: app setup tasks
  include_role: 
    name: common
    tasks_from: app-setup

- name: nodejs tasks
  include_role:
    name: common
    tasks_from: nodejs


- name: copying cart service file
  ansible.builtin.template:
    src:  cart.service.j2
    dest: /etc/systemd/system/cart.service          


- name: systemd tasks
  include_role:
    name: common
    tasks_from: systemd         